// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_norty144.Models;

namespace Mission06_norty144.Migrations
{
    [DbContext(typeof(MovieDataContext))]
    [Migration("20230221215852_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_norty144.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Action"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Adventure"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Comedy"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Drama"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Horror"
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Romance"
                        },
                        new
                        {
                            CategoryID = 7,
                            CategoryName = "Thriller"
                        },
                        new
                        {
                            CategoryID = 8,
                            CategoryName = "Fantasy"
                        },
                        new
                        {
                            CategoryID = 9,
                            CategoryName = "Mystery"
                        },
                        new
                        {
                            CategoryID = 10,
                            CategoryName = "Western"
                        },
                        new
                        {
                            CategoryID = 11,
                            CategoryName = "Sports"
                        },
                        new
                        {
                            CategoryID = 12,
                            CategoryName = "Science Fiction"
                        },
                        new
                        {
                            CategoryID = 13,
                            CategoryName = "Musical"
                        });
                });

            modelBuilder.Entity("Mission06_norty144.Models.MovieResponse", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .HasColumnType("TEXT");

                    b.HasKey("MovieId");

                    b.HasIndex("CategoryID");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            CategoryID = 1,
                            Director = "Tim Burton",
                            Edited = false,
                            LentTo = "",
                            Notes = "",
                            Rating = "PG-13",
                            Title = "Batman",
                            Year = "1989"
                        },
                        new
                        {
                            MovieId = 2,
                            CategoryID = 1,
                            Director = "Chris Columbus",
                            Edited = true,
                            LentTo = "",
                            Notes = "",
                            Rating = "PG",
                            Title = "Harry Potter and the Chamber of Secrets",
                            Year = "2002"
                        },
                        new
                        {
                            MovieId = 3,
                            CategoryID = 1,
                            Director = "Bryan Singer",
                            Edited = false,
                            LentTo = "",
                            Notes = "",
                            Rating = "PG-13",
                            Title = "X-Men",
                            Year = "2000"
                        });
                });

            modelBuilder.Entity("Mission06_norty144.Models.MovieResponse", b =>
                {
                    b.HasOne("Mission06_norty144.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
